### ISSUE TITLE
`visualize(::AtomGraph)` should write to file

### ISSUE THREAD

**Issue by rkurchin** [Chemellia/ChemistryFeaturization.jl#109]
This should be easy enough. I think @sakshi-satyanand is going to take a crack at this :)

**Comment by DhairyaLGandhi** [comment]
There's a separate `write` or `save` for svg/ png files already right? Why not use that instead?

**Comment by jonathanmfung** [comment]
I have ported this issue to Chemellia/AtomGraphs.jl#5, as this package no longer directly handles `AtomGraphs`. Please close.
