### ISSUE TITLE
Make docs!

### ISSUE THREAD

**Issue by rkurchin** [Chemellia/ChemistryFeaturization.jl#17]
Can use GitHub wiki to start with

**Comment by thazhemadam** [comment]
@rkurchin seeing how I've already begun working on this, could you officially assign this to me, so that nobody else has to spend time on this?

**Comment by rkurchin** [comment]
Just noting that I haven't forgotten about editing and deploying these but I'm putting it on the back burner until we finish the redesign because a lot of stuff will have to be added/changed at that point anyway...

**Comment by thazhemadam** [comment]
Just a note here to also add examples of the different ways objects can be initialised for the types defined post re-designing.

**Comment by rkurchin** [comment]
another note that we have to update the README

**Comment by rkurchin** [comment]
and flesh out examples, e.g. `custom_feature.jl` and perhaps some other things?
