### ISSUE TITLE
Fix Windows CI

### ISSUE THREAD

**Issue by rkurchin** [Chemellia/ChemistryFeaturization.jl#41]
Note to self to eventually go back and troubleshoot the `windows-latest` runner in the CI, which is currently removed entirely. This will likely be easier if/when we're able to excise some more Python dependencies, since the last time around the errors had to do with numpy C-extensions...

**Comment by thazhemadam** [comment]
Reopening because this needs to be fixed _properly_, and the current 'fix' breaks ] build sometimes.

+CC @DhairyaLGandhi as reverting the current 'fix' would break Windows CI as well.
