### ISSUE TITLE
more features, sources, allow user to add features

### ISSUE THREAD

**Issue by rkurchin** [Chemellia/ChemistryFeaturization.jl#5]
* would be good to showcase that it's easy to add other features to lookup table
* also maybe add oxidation-state-dependent things

**Comment by adinhobl** [comment]
When this says "load sources", are you referring to the `deepchem.molnet.load_*source*(featurizers, splitters)` for each of the molnet datasources? There are also other options methods for loading from disks, dataframes, and arrays

**Comment by rkurchin** [comment]
I'm not familiar enough with molnet to know exactly what you're talking about there, but what I'm referring to here is including more features (from other data sources) in the built-in data tables for the package. Currently it's mostly just atomic features from pymatgen and I think a few I pulled from matminer too.

**Comment by adinhobl** [comment]
I see. Deepchem contains methods to load the various MoleculeNet [datasets](http://moleculenet.ai/datasets-1) and preprocess the data with splitters and featurizers.

**Comment by rkurchin** [comment]
Adding to this that it would be good also to build a way for a user to add in their own data source for atomic features that could hook into the automated vector-building functions. One could already in principle add user-sourced features but only by "manually" providing either feature matrices or at least vectors directly, so you couldn't use the functions that build features for you if only a list of feature names is provided.

**Comment by rkurchin** [comment]
This is covered by restructure PR and I neglected to link it, closing.
